from envrax import register_suite

from mujorax.envs import (
    AcrobotSwingupEnv,
    AcrobotSwingupSparseEnv,
    BallInCupEnv,
    CartpoleBalanceEnv,
    CartpoleBalanceSparseEnv,
    CartpoleSwingupEnv,
    CartpoleSwingupSparseEnv,
    CheetahRunEnv,
    FingerSpinEnv,
    FingerTurnEasyEnv,
    FingerTurnHardEnv,
    FishSwimEnv,
    HopperHopEnv,
    HopperStandEnv,
    HumanoidRunEnv,
    HumanoidStandEnv,
    HumanoidWalkEnv,
    MjxPlaygroundConfig,
    MjxPlaygroundEnv,
    MjxPlaygroundState,
    PendulumSwingupEnv,
    PointMassEnv,
    ReacherEasyEnv,
    ReacherHardEnv,
    SwimmerSwimmer6Env,
    WalkerRunEnv,
    WalkerStandEnv,
    WalkerWalkEnv,
)
from mujorax.suite import DmControlSuite

register_suite(DmControlSuite())

__all__ = [
    "AcrobotSwingupEnv",
    "AcrobotSwingupSparseEnv",
    "BallInCupEnv",
    "CartpoleBalanceEnv",
    "CartpoleBalanceSparseEnv",
    "CartpoleSwingupEnv",
    "CartpoleSwingupSparseEnv",
    "CheetahRunEnv",
    "DmControlSuite",
    "FingerSpinEnv",
    "FingerTurnEasyEnv",
    "FingerTurnHardEnv",
    "FishSwimEnv",
    "HopperHopEnv",
    "HopperStandEnv",
    "HumanoidRunEnv",
    "HumanoidStandEnv",
    "HumanoidWalkEnv",
    "MjxPlaygroundConfig",
    "MjxPlaygroundEnv",
    "MjxPlaygroundState",
    "PendulumSwingupEnv",
    "PointMassEnv",
    "ReacherEasyEnv",
    "ReacherHardEnv",
    "SwimmerSwimmer6Env",
    "WalkerRunEnv",
    "WalkerStandEnv",
    "WalkerWalkEnv",
]
